<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="AbstractState" Id="{fa262302-fbab-4380-bea0-f5c030f48e7a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT AbstractState IMPLEMENTS I_State
VAR_INPUT
	ipStatehandler: I_Statehandler;
END_VAR
VAR
	fbTON: TON;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{e82d3211-c556-47a7-a96b-fd256a0d2ee5}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	ipStatehandler: I_Statehandler;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.ipStatehandler := ipStatehandler;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Handle" Id="{74617af7-e3cd-4159-9f51-aa4c332d44e9}">
      <Declaration><![CDATA[METHOD ABSTRACT Handle : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="AbstractState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="AbstractState.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="AbstractState.Handle">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>